- name: creating catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: disable  nodejs 
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs:20
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: creating folder
    ansible.builtin.file:
      path: /app
      state: directory

  - name: downloading content
    ansible.builtin.get_url: 
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip

  - name: creating system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      home: /app
      system: true

  - name: extract code
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: installing depedencies
    community.general.npm:
      path: /app
  
  - name: copying service file    
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: reloading service
    ansible.builtin.systemd_service:
      daemon-reload: true

  - name: starting service  
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes

  - name: copying mongod repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongod.repo

  - name: installing mongodb client 
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present
  
  - name: checking data loaded
    ansible.builtin.command: mongosh --host mongodb.sharkdev.shop --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: command_output
  
  - name: printing output
    ansible.builtin.command:
      msg: "{{ command_output }}"

  - name: loading data
    ansible.builtin.shell: mongosh --host mongodb.sharkdev.shop < /app/db/master-data.js
    when: command_output.stdout | int < 0


