- name: dispatch
  hosts: dispatch
  become: yes
  tasks:
  - name: installing golang
    ansible.builtin.dnf:
      name: golang
      state: present

  - name: creating folder
    ansible.builtin.file:
      path: /app
      state: directory

  - name: downloading content
    ansible.builtin.get_url: 
      url: https://roboshop-artifacts.s3.amazonaws.com/dispatch-v3.zip
      dest: /tmp/dispatch.zip

  - name: creating system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      home: /app
      system: true

  - name: extract code
    ansible.builtin.unarchive:
      src: /tmp/dispatch.zip
      dest: /app
      remote_src: yes

  - name: Initialize Go module
    ansible.builtin.command: go mod init dispatch
    args:
      chdir: /app
    when: not ansible_check_mode

  - name: Download dependencies
    ansible.builtin.command: go get
    args:
      chdir: /app

  - name: Build Go project
    ansible.builtin.command: go build
    args:
      chdir: /app

  - name: copying service file    
    ansible.builtin.copy:
      src: dispatch.service
      dest: /etc/systemd/system/dispatch.service

  - name: reloading service
    ansible.builtin.systemd_service:
      daemon-reload: true

  - name: starting service  
    ansible.builtin.service:
      name: dispatch
      state: started
      enabled: yes